/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.programming.lan.Interfaz;

import com.mycompany.programming.lan.Gramatica.pilaLALR;
import com.mycompany.programming.lan.Gramatica.pilaLALR.movimiento;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JButton;

/**
 *
 * @author jhonny
 */
public class Content_pila extends javax.swing.JPanel {

    /**
     * Creates new form Content_pila
     */
    public Content_pila() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        p2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        p3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        p1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        acciones = new javax.swing.JTextArea();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, -1, -1));

        javax.swing.GroupLayout p2Layout = new javax.swing.GroupLayout(p2);
        p2.setLayout(p2Layout);
        p2Layout.setHorizontalGroup(
            p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 794, Short.MAX_VALUE)
        );
        p2Layout.setVerticalGroup(
            p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 407, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(p2);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 810, 90));

        javax.swing.GroupLayout p3Layout = new javax.swing.GroupLayout(p3);
        p3.setLayout(p3Layout);
        p3Layout.setHorizontalGroup(
            p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 804, Short.MAX_VALUE)
        );
        p3Layout.setVerticalGroup(
            p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 407, Short.MAX_VALUE)
        );

        jScrollPane3.setViewportView(p3);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, 820, 90));

        jLabel2.setText("Pila transiciones");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, -1, -1));

        jLabel3.setText("Pila de tokens");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 510, -1, -1));

        javax.swing.GroupLayout p1Layout = new javax.swing.GroupLayout(p1);
        p1.setLayout(p1Layout);
        p1Layout.setHorizontalGroup(
            p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 794, Short.MAX_VALUE)
        );
        p1Layout.setVerticalGroup(
            p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 407, Short.MAX_VALUE)
        );

        jScrollPane4.setViewportView(p1);

        add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 810, 90));

        jLabel1.setText("Pila entrada");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, -1, -1));

        jButton1.setText("Next");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 560, 80, -1));

        jButton2.setText("previo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 560, -1, -1));

        acciones.setColumns(20);
        acciones.setRows(5);
        jScrollPane5.setViewportView(acciones);

        add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 50, -1, 210));
    }// </editor-fold>//GEN-END:initComponents


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (this.contador >= this.listado.size()) {
            return;
        }
        movimiento x = this.listado.get(contador);
        this.acciones.setText(x.dato);
        if (x.p1 != null) {
            if (pos1 != 0) {
                pila1[pos1 - 1].setBackground(null);
            }
            pila1[pos1] = new JButton(x.p1.getPilaCheck());
            pila1[pos1].setBackground(Color.red);
            this.p1.add(pila1[pos1]);
            pos1++;
            this.p1.repaint();
            this.p1.revalidate();
        }
        if (x.p2 != null) {
            if(x.p2.reduce==-15){
            }else{
            if (x.p2.reduce <= 0) {
                if (pos2 != 0) {
                    pila2[pos2 - 1].setBackground(null);
                }
                pila2[pos2] = new JButton(String.valueOf(x.p2.addTrans));
                this.p2.add(pila2[pos2]);
                pila2[pos2].setBackground(Color.YELLOW);
                pos2++;
            } else {
                for (int i = 0; i < x.p2.reduce; i++) {
                    this.p2.remove(pila2[pos2 - 1]);
                    x.p2.add(pila2[pos2 - 1].getText());
                    pos2--;
                }
                if (pos2 != 0) {
                    pila2[pos2 - 1].setBackground(Color.YELLOW);
                }
            }}

            this.p2.repaint();
            this.p2.revalidate();
        }
        if (x.p3 != null) {
           {
            if (x.p3.reduce <= 0) {
                if (pos3 != 0) {
                    pila3[pos3 - 1].setBackground(null);
                }
                pila3[pos3] = new JButton(x.p3.tokenAdd);
                this.p3.add(pila3[pos3]);
                pila3[pos3].setBackground(Color.GREEN);
                pos3++;
            } else {
                try{
                for (int i = 0; i < x.p3.reduce; i++) {
                    this.p3.remove(pila3[pos3 - 1]);
                    x.p3.add(pila3[pos3 - 1].getText());
                    pos3--;
                }
                pila3[pos3] = new JButton(x.p3.tokenAdd);
                pila3[pos3].setBackground(Color.GREEN);
                this.p3.add(pila3[pos3]);
                pos3++;
                }catch(Exception ex){}
                
            }
            }
            

            this.p3.repaint();
            this.p3.revalidate();
        }
        contador++;
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (this.contador < 0) {
            return;
        }
        this.contador--;

        movimiento x = this.listado.get(contador);
        this.acciones.setText(x.dato);
        if (x.p1 != null) {
            if (pos1 != 0) {
                this.p1.remove(pila1[pos1 - 1]);
                pos1--;
                if (pos1 != 0) {
                    this.pila1[pos1 - 1].setBackground(Color.red);
                }
                this.p1.repaint();
                this.p1.revalidate();
            }
        }

        if (x.p2 != null && pos2 != 0) {
            if(x.p2.reduce==-15){
            }else{
            if (x.p2.reduce <= 0) {
                this.p2.remove(pila2[pos2 - 1]);
                pos2--;
                if (pos2 != 0) {
                    pila2[pos2 - 1].setBackground(Color.YELLOW);
                }

            } else {
                String vect[] = x.p2.removes.split(",");
                pila2[pos2 - 1].setBackground(null);
                for (int i = 0; i < x.p2.reduce; i++) {
                    pila2[pos2] = new JButton(vect[i]);
                    pila2[pos2].setBackground(null);
                    this.p2.add(pila2[pos2]);
                    pos2++;
                }
                pila2[pos2 - 1].setBackground(Color.YELLOW);
            }
            }
            

            this.p2.repaint();
            this.p2.revalidate();
        }

        if (x.p3 != null & pos3 != 0) {
            if (x.p3.reduce <= 0) {
                this.p3.remove(pila3[pos3 - 1]);
                pos3--;
                if (pos3 != 0) {
                    pila3[pos3-1].setBackground(Color.GREEN);
                }

            } else {
                this.p3.remove(pila3[pos3 - 1]);
                pos3--;
                String vect[] = x.p3.removes.split(",");
                for (int i = 0; i < x.p3.reduce; i++) {
                    pila3[pos3] = new JButton(vect[i]);
                    this.p3.add(pila3[pos3]);
                    pos3++;
                }
               
                pila3[pos3-1].setBackground(Color.GREEN);
            }

            this.p3.repaint();
            this.p3.revalidate();
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    JButton pila1[], pila2[], pila3[];
    int pos1 = 0, pos2 = 0, pos3 = 0, contador = 0;
    ArrayList<pilaLALR.movimiento> listado;

    public void init(int x, ArrayList<movimiento> mv) {
        this.acciones.setEditable(false);
        this.listado = mv;
        pila1 = new JButton[x];
        pila2 = new JButton[x];
        pila3 = new JButton[x];
        this.p1.setLayout(new java.awt.GridLayout(1, x));
        this.p2.setLayout(new java.awt.GridLayout(1, x));
        this.p3.setLayout(new java.awt.GridLayout(1, x));

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea acciones;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JPanel p1;
    private javax.swing.JPanel p2;
    private javax.swing.JPanel p3;
    // End of variables declaration//GEN-END:variables
}
